# Generated by Django 6.0.3 on 2026-03-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completed_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="todo/completed_images"
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="todo/no_image/NO-IMAGE.gif",
                null=True,
                upload_to="todo/thumbnails",
            ),
        ),
    ]
